# Лабораторна №9. Тензори. Нейронні мережі та табличні дані.
## Робота з тензорами.

### Імпортуйте необхідні біліотеки.

In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline



In [55]:
np.random.seed(42) # запустіть цю клітинку, щоб ваші результати співпадали з тим, що наведено у прикладі.
torch.manual_seed(42)

### Створіть numpy масив який містить 12 випадкових цілих чисел в межах від 0 (включно) до 12 (невключно).

In [56]:
# пишіть код тут.
arr = np.random.randint(0, 12, size=12, dtype=np.int32)
print(arr)

[ 6  3 10  7  4  6  9  2  6 10 10  7]


[ 6  3 10  7  4  6  9  2  6 10 10  7]


### Створіть тензор з масиву, створеного вище.

In [57]:
# пишіть код тут.
x = torch.from_numpy(arr)
print(x)
print(x.dtype)

tensor([ 6,  3, 10,  7,  4,  6,  9,  2,  6, 10, 10,  7], dtype=torch.int32)
torch.int32


tensor([ 6,  3, 10,  7,  4,  6,  9,  2,  6, 10, 10,  7], dtype=torch.int32)


### Змініть тип тензора на int64.

In [58]:
# пишіть код тут.
x = x.type(torch.float64)
print(x.dtype)

torch.float64


In [8]:
x = x.long()
print(x.type())

torch.LongTensor


### Змініть розміри тензора на 3x4.

In [59]:
# пишіть код тут.
X = x.reshape(3, 4)
X

tensor([[ 6.,  3., 10.,  7.],
        [ 4.,  6.,  9.,  2.],
        [ 6., 10., 10.,  7.]], dtype=torch.float64)

tensor([[ 6,  3, 10,  7],
        [ 4,  6,  9,  2],
        [ 6, 10, 10,  7]])


### Виведіть значення 4 стовпчика.

In [ ]:
# пишіть код тут.
X[:, 3].unsqueeze(1)

tensor([[7.],
        [2.],
        [7.]], dtype=torch.float64)

tensor([[7],
        [2],
        [7]])

### Без зміни тензора, поверніть тензор, у якому є квадрати значеннь з основного тензора.

In [63]:
# пишіть код тут.
X ** 2
 

tensor([[ 36.,   9., 100.,  49.],
        [ 16.,  36.,  81.,   4.],
        [ 36., 100., 100.,  49.]], dtype=torch.float64)

tensor([[ 36,   9, 100,  49],
        [ 16,  36,  81,   4],
        [ 36, 100, 100,  49]])

### Створіть ще одни тензор, з такими ж елементами, як у основному тензорі, але який можна буде перемножити з основним тензором.
Використайте PyTorch для створення тензора.

In [100]:
# пишіть код тут.
X2 = np.random.randint(0, 12, size=(3, 4), dtype=np.int32)
X2 = torch.from_numpy(X2)
X2.reshape(4, 3)

tensor([[ 8, 11,  6],
        [ 8,  7, 11],
        [ 1,  0,  6],
        [ 6,  7,  4]], dtype=torch.int32)

In [101]:
X = X.int()
X

tensor([[ 6,  3, 10],
        [ 7,  4,  6],
        [ 9,  2,  6],
        [10, 10,  7]], dtype=torch.int32)

tensor([[ 6, 11,  4],
        [10,  6, 11],
        [ 4,  8, 10],
        [ 5, 10, 10]])


### Знайдіть добуток двох матриць: основної, та створеної на минулому кроці.

In [102]:
# пишіть код тут.
X @ X2

tensor([[129, 159, 109,  88],
        [120, 157,  88,  80],
        [122, 157,  98,  96],
        [192, 262, 119, 108]], dtype=torch.int32)

tensor([[141, 234, 227],
        [130, 172, 192],
        [211, 276, 304]])


## Нейромережі.
Використайте один з наборів даних, які вже використовувались у попередніх лабораторних роботах. Проведіть аналіз даних, та розділіть їх на незалежні та цільові змінні. Створіть моделі штучної нейронної мережі, які зможуть прогнозувати цільову змінну використовуючи різні фреймворки. Мережі мають містити як мінімум один прихований рівень.